export enum IssueStatus {
    BACKLOG = 'BACKLOG',
    PLANING = 'PLANING',
    DEVELOPMENT_DOING = 'DEVELOPMENT_DOING',
    DEVELOPMENT_DONE = 'DEVELOPMENT_DONE',
    TESTING_DOING = 'TESTING_DOING',
    TESTING_FAILD = 'TESTING_FAILD',
    TESTING_SUCCESSFUL = 'TESTING_SUCCESSFUL'
}
