spring:
  datasource:
    password: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/szakdoga '
    username: szakdoga
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/data/changelog/db.changelog-master.xml
    enabled: true

